name: Backend Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'starter/backend/**'  # Trigger only if files in the frontend directory change
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12
  IMAGE_NAME: mp-backend
  IMAGE_TAG: latest
  BACKEND_ECR: 468154422986.dkr.ecr.us-east-1.amazonaws.com

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv flake8
          pipenv install

      - name: Run Lint
        run: pipenv run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Testing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pytest
          pipenv install

      - name: Run Backend Tests
        run: pipenv run test

  build:
    name: Build Docker Image
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Build
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
