name: Frontend Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'starter/frontend/**'  # Trigger only if files in the frontend directory change
  workflow_dispatch:

env:
  NODE_VERSION: 18.18.0
  IMAGE_NAME: frontend
  IMAGE_TAG: latest
  FRONTEND_ECR: 468154422986.dkr.ecr.us-east-1.amazonaws.com


jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Run lint
        run: npm run lint

  test:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: | 
          npm ci
          npm install prettier --save-dev

      - name: Run tests
        run: CI=true npm test

  build:
    name: Build and Deploy
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Build
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
